apiVersion: apps/v1
kind: Deployment
metdata:
  name: catalogue
  namespace: suraj
  labels:
    project: suraj
    env: dev
    component: db

spec:
  replicas: 3
  selector:
    matchLabels:
      project: suraj
      env: dev
      component: db

  template:
    metadata:
      labels:
        project: suraj
        env: dev
        component: db

    spec:
      containers:
      - name: catalogue
        image: 296062550816.dkr.ecr.us-east-1.amazonaws.com/suraj/dev/catalogue:1.0
        imagePullPolicy: Always
        envFrom:
        - name:
            configMapRef:
              name: catalogue-config

  
---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: suraj

spec:
  selector:
    project: suraj
    env: dev
    component: db

  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: suraj

data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"